version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: elis
      POSTGRES_PASSWORD: e1l1s1Z8b
      POSTGRES_DB: naapuri
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: